// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nmt.Infrastructure.Data.Postgres;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nmt.Infrastructure.Data.Postgres.Migrations
{
    [DbContext(typeof(PostgresDbContext))]
    [Migration("20230101083929_IdentityInitial")]
    partial class IdentityInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityRoleClaim<Guid>");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Nmt.Domain.Models.BlockedIp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Ip")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BlockedIps");
                });

            modelBuilder.Entity("Nmt.Domain.Models.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MachineSpecificStamp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "MachineSpecificStamp");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Nmt.Domain.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9252b6f4-5c44-411d-85b4-9e96e3648e44"),
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = new Guid("b03c655f-fb29-40c9-a0c2-5fe29349c9b0"),
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Nmt.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("UserName");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Nmt.Domain.Models.RoleClaim", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>");

                    b.HasDiscriminator().HasValue("RoleClaim");

                    b.HasData(
                        new
                        {
                            Id = 22,
                            ClaimType = "Permissions",
                            ClaimValue = "1",
                            RoleId = new Guid("9252b6f4-5c44-411d-85b4-9e96e3648e44")
                        },
                        new
                        {
                            Id = 23,
                            ClaimType = "Permissions",
                            ClaimValue = "2",
                            RoleId = new Guid("9252b6f4-5c44-411d-85b4-9e96e3648e44")
                        },
                        new
                        {
                            Id = 24,
                            ClaimType = "Permissions",
                            ClaimValue = "3",
                            RoleId = new Guid("9252b6f4-5c44-411d-85b4-9e96e3648e44")
                        },
                        new
                        {
                            Id = 25,
                            ClaimType = "Permissions",
                            ClaimValue = "5",
                            RoleId = new Guid("9252b6f4-5c44-411d-85b4-9e96e3648e44")
                        },
                        new
                        {
                            Id = 26,
                            ClaimType = "Permissions",
                            ClaimValue = "6",
                            RoleId = new Guid("9252b6f4-5c44-411d-85b4-9e96e3648e44")
                        },
                        new
                        {
                            Id = 27,
                            ClaimType = "Permissions",
                            ClaimValue = "9",
                            RoleId = new Guid("9252b6f4-5c44-411d-85b4-9e96e3648e44")
                        },
                        new
                        {
                            Id = 28,
                            ClaimType = "Permissions",
                            ClaimValue = "10",
                            RoleId = new Guid("9252b6f4-5c44-411d-85b4-9e96e3648e44")
                        },
                        new
                        {
                            Id = 29,
                            ClaimType = "Permissions",
                            ClaimValue = "11",
                            RoleId = new Guid("9252b6f4-5c44-411d-85b4-9e96e3648e44")
                        },
                        new
                        {
                            Id = 30,
                            ClaimType = "Permissions",
                            ClaimValue = "12",
                            RoleId = new Guid("9252b6f4-5c44-411d-85b4-9e96e3648e44")
                        },
                        new
                        {
                            Id = 31,
                            ClaimType = "Permissions",
                            ClaimValue = "1",
                            RoleId = new Guid("b03c655f-fb29-40c9-a0c2-5fe29349c9b0")
                        },
                        new
                        {
                            Id = 32,
                            ClaimType = "Permissions",
                            ClaimValue = "2",
                            RoleId = new Guid("b03c655f-fb29-40c9-a0c2-5fe29349c9b0")
                        },
                        new
                        {
                            Id = 33,
                            ClaimType = "Permissions",
                            ClaimValue = "3",
                            RoleId = new Guid("b03c655f-fb29-40c9-a0c2-5fe29349c9b0")
                        },
                        new
                        {
                            Id = 34,
                            ClaimType = "Permissions",
                            ClaimValue = "4",
                            RoleId = new Guid("b03c655f-fb29-40c9-a0c2-5fe29349c9b0")
                        },
                        new
                        {
                            Id = 35,
                            ClaimType = "Permissions",
                            ClaimValue = "5",
                            RoleId = new Guid("b03c655f-fb29-40c9-a0c2-5fe29349c9b0")
                        },
                        new
                        {
                            Id = 36,
                            ClaimType = "Permissions",
                            ClaimValue = "6",
                            RoleId = new Guid("b03c655f-fb29-40c9-a0c2-5fe29349c9b0")
                        },
                        new
                        {
                            Id = 37,
                            ClaimType = "Permissions",
                            ClaimValue = "7",
                            RoleId = new Guid("b03c655f-fb29-40c9-a0c2-5fe29349c9b0")
                        },
                        new
                        {
                            Id = 38,
                            ClaimType = "Permissions",
                            ClaimValue = "8",
                            RoleId = new Guid("b03c655f-fb29-40c9-a0c2-5fe29349c9b0")
                        },
                        new
                        {
                            Id = 39,
                            ClaimType = "Permissions",
                            ClaimValue = "9",
                            RoleId = new Guid("b03c655f-fb29-40c9-a0c2-5fe29349c9b0")
                        },
                        new
                        {
                            Id = 40,
                            ClaimType = "Permissions",
                            ClaimValue = "10",
                            RoleId = new Guid("b03c655f-fb29-40c9-a0c2-5fe29349c9b0")
                        },
                        new
                        {
                            Id = 41,
                            ClaimType = "Permissions",
                            ClaimValue = "11",
                            RoleId = new Guid("b03c655f-fb29-40c9-a0c2-5fe29349c9b0")
                        },
                        new
                        {
                            Id = 42,
                            ClaimType = "Permissions",
                            ClaimValue = "12",
                            RoleId = new Guid("b03c655f-fb29-40c9-a0c2-5fe29349c9b0")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Nmt.Domain.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Nmt.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Nmt.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Nmt.Domain.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nmt.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Nmt.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nmt.Domain.Models.BlockedIp", b =>
                {
                    b.HasOne("Nmt.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Nmt.Domain.Models.Device", b =>
                {
                    b.HasOne("Nmt.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
