// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: ip_filters.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IpFiltersClient is the client API for IpFilters service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IpFiltersClient interface {
	GetIpFilters(ctx context.Context, in *GetIpFiltersRequest, opts ...grpc.CallOption) (*IpFiltersResponse, error)
}

type ipFiltersClient struct {
	cc grpc.ClientConnInterface
}

func NewIpFiltersClient(cc grpc.ClientConnInterface) IpFiltersClient {
	return &ipFiltersClient{cc}
}

func (c *ipFiltersClient) GetIpFilters(ctx context.Context, in *GetIpFiltersRequest, opts ...grpc.CallOption) (*IpFiltersResponse, error) {
	out := new(IpFiltersResponse)
	err := c.cc.Invoke(ctx, "/ip_filters.IpFilters/GetIpFilters", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IpFiltersServer is the server API for IpFilters service.
// All implementations must embed UnimplementedIpFiltersServer
// for forward compatibility
type IpFiltersServer interface {
	GetIpFilters(context.Context, *GetIpFiltersRequest) (*IpFiltersResponse, error)
	mustEmbedUnimplementedIpFiltersServer()
}

// UnimplementedIpFiltersServer must be embedded to have forward compatible implementations.
type UnimplementedIpFiltersServer struct {
}

func (UnimplementedIpFiltersServer) GetIpFilters(context.Context, *GetIpFiltersRequest) (*IpFiltersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIpFilters not implemented")
}
func (UnimplementedIpFiltersServer) mustEmbedUnimplementedIpFiltersServer() {}

// UnsafeIpFiltersServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IpFiltersServer will
// result in compilation errors.
type UnsafeIpFiltersServer interface {
	mustEmbedUnimplementedIpFiltersServer()
}

func RegisterIpFiltersServer(s grpc.ServiceRegistrar, srv IpFiltersServer) {
	s.RegisterService(&IpFilters_ServiceDesc, srv)
}

func _IpFilters_GetIpFilters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIpFiltersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IpFiltersServer).GetIpFilters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ip_filters.IpFilters/GetIpFilters",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IpFiltersServer).GetIpFilters(ctx, req.(*GetIpFiltersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IpFilters_ServiceDesc is the grpc.ServiceDesc for IpFilters service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IpFilters_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ip_filters.IpFilters",
	HandlerType: (*IpFiltersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetIpFilters",
			Handler:    _IpFilters_GetIpFilters_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ip_filters.proto",
}
