// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ip_filters.proto

package grpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IpFilterModel struct {
	Ip                   uint32   `protobuf:"varint,1,opt,name=ip,proto3" json:"ip,omitempty"`
	FilterAction         int32    `protobuf:"varint,4,opt,name=filterAction,proto3" json:"filterAction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IpFilterModel) Reset()         { *m = IpFilterModel{} }
func (m *IpFilterModel) String() string { return proto.CompactTextString(m) }
func (*IpFilterModel) ProtoMessage()    {}
func (*IpFilterModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_91b7d9b8e1c44ff2, []int{0}
}

func (m *IpFilterModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IpFilterModel.Unmarshal(m, b)
}
func (m *IpFilterModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IpFilterModel.Marshal(b, m, deterministic)
}
func (m *IpFilterModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IpFilterModel.Merge(m, src)
}
func (m *IpFilterModel) XXX_Size() int {
	return xxx_messageInfo_IpFilterModel.Size(m)
}
func (m *IpFilterModel) XXX_DiscardUnknown() {
	xxx_messageInfo_IpFilterModel.DiscardUnknown(m)
}

var xxx_messageInfo_IpFilterModel proto.InternalMessageInfo

func (m *IpFilterModel) GetIp() uint32 {
	if m != nil {
		return m.Ip
	}
	return 0
}

func (m *IpFilterModel) GetFilterAction() int32 {
	if m != nil {
		return m.FilterAction
	}
	return 0
}

type GetIpFiltersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetIpFiltersRequest) Reset()         { *m = GetIpFiltersRequest{} }
func (m *GetIpFiltersRequest) String() string { return proto.CompactTextString(m) }
func (*GetIpFiltersRequest) ProtoMessage()    {}
func (*GetIpFiltersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_91b7d9b8e1c44ff2, []int{1}
}

func (m *GetIpFiltersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIpFiltersRequest.Unmarshal(m, b)
}
func (m *GetIpFiltersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIpFiltersRequest.Marshal(b, m, deterministic)
}
func (m *GetIpFiltersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIpFiltersRequest.Merge(m, src)
}
func (m *GetIpFiltersRequest) XXX_Size() int {
	return xxx_messageInfo_GetIpFiltersRequest.Size(m)
}
func (m *GetIpFiltersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIpFiltersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetIpFiltersRequest proto.InternalMessageInfo

type IpFiltersResponse struct {
	IpFilters            []*IpFilterModel `protobuf:"bytes,1,rep,name=ipFilters,proto3" json:"ipFilters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *IpFiltersResponse) Reset()         { *m = IpFiltersResponse{} }
func (m *IpFiltersResponse) String() string { return proto.CompactTextString(m) }
func (*IpFiltersResponse) ProtoMessage()    {}
func (*IpFiltersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_91b7d9b8e1c44ff2, []int{2}
}

func (m *IpFiltersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IpFiltersResponse.Unmarshal(m, b)
}
func (m *IpFiltersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IpFiltersResponse.Marshal(b, m, deterministic)
}
func (m *IpFiltersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IpFiltersResponse.Merge(m, src)
}
func (m *IpFiltersResponse) XXX_Size() int {
	return xxx_messageInfo_IpFiltersResponse.Size(m)
}
func (m *IpFiltersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IpFiltersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IpFiltersResponse proto.InternalMessageInfo

func (m *IpFiltersResponse) GetIpFilters() []*IpFilterModel {
	if m != nil {
		return m.IpFilters
	}
	return nil
}

func init() {
	proto.RegisterType((*IpFilterModel)(nil), "ip_filters.IpFilterModel")
	proto.RegisterType((*GetIpFiltersRequest)(nil), "ip_filters.GetIpFiltersRequest")
	proto.RegisterType((*IpFiltersResponse)(nil), "ip_filters.IpFiltersResponse")
}

func init() {
	proto.RegisterFile("ip_filters.proto", fileDescriptor_91b7d9b8e1c44ff2)
}

var fileDescriptor_91b7d9b8e1c44ff2 = []byte{
	// 209 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xc8, 0x2c, 0x88, 0x4f,
	0xcb, 0xcc, 0x29, 0x49, 0x2d, 0x2a, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x42, 0x88,
	0x28, 0x39, 0x73, 0xf1, 0x7a, 0x16, 0xb8, 0x81, 0x39, 0xbe, 0xf9, 0x29, 0xa9, 0x39, 0x42, 0x7c,
	0x5c, 0x4c, 0x99, 0x05, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xbc, 0x41, 0x4c, 0x99, 0x05, 0x42, 0x4a,
	0x5c, 0x3c, 0x10, 0xb5, 0x8e, 0xc9, 0x25, 0x99, 0xf9, 0x79, 0x12, 0x2c, 0x0a, 0x8c, 0x1a, 0xac,
	0x41, 0x28, 0x62, 0x4a, 0xa2, 0x5c, 0xc2, 0xee, 0xa9, 0x25, 0x30, 0x73, 0x8a, 0x83, 0x52, 0x0b,
	0x4b, 0x53, 0x8b, 0x4b, 0x94, 0x7c, 0xb8, 0x04, 0x91, 0xc4, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53,
	0x85, 0xcc, 0xb9, 0x38, 0x33, 0x61, 0x82, 0x12, 0x8c, 0x0a, 0xcc, 0x1a, 0xdc, 0x46, 0x92, 0x7a,
	0x48, 0x4e, 0x44, 0x71, 0x4d, 0x10, 0x42, 0xad, 0x51, 0x34, 0x17, 0x27, 0xdc, 0x34, 0x21, 0x3f,
	0x2e, 0x1e, 0x64, 0x1b, 0x85, 0xe4, 0x91, 0x8d, 0xc0, 0xe2, 0x16, 0x29, 0x59, 0x6c, 0x76, 0xc0,
	0x5d, 0xe5, 0x24, 0x13, 0xc5, 0x51, 0x90, 0x9d, 0xae, 0x9f, 0x5e, 0x54, 0x90, 0xbc, 0x8a, 0x89,
	0xdf, 0x2f, 0xb7, 0x44, 0xcf, 0xbd, 0xa8, 0x20, 0x59, 0x2f, 0x00, 0x14, 0x5e, 0xc5, 0x49, 0x6c,
	0xe0, 0x70, 0x33, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x8a, 0xe9, 0xcb, 0x65, 0x4b, 0x01, 0x00,
	0x00,
}
