// Code generated by protoc-gen-go. DO NOT EDIT.
// source: packets.proto

package grpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PacketModel struct {
	Ip                   uint32               `protobuf:"varint,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Size                 uint32               `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Protocol             uint32               `protobuf:"varint,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Status               uint32               `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PacketModel) Reset()         { *m = PacketModel{} }
func (m *PacketModel) String() string { return proto.CompactTextString(m) }
func (*PacketModel) ProtoMessage()    {}
func (*PacketModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_e370a687125f60cd, []int{0}
}

func (m *PacketModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PacketModel.Unmarshal(m, b)
}
func (m *PacketModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PacketModel.Marshal(b, m, deterministic)
}
func (m *PacketModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PacketModel.Merge(m, src)
}
func (m *PacketModel) XXX_Size() int {
	return xxx_messageInfo_PacketModel.Size(m)
}
func (m *PacketModel) XXX_DiscardUnknown() {
	xxx_messageInfo_PacketModel.DiscardUnknown(m)
}

var xxx_messageInfo_PacketModel proto.InternalMessageInfo

func (m *PacketModel) GetIp() uint32 {
	if m != nil {
		return m.Ip
	}
	return 0
}

func (m *PacketModel) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *PacketModel) GetProtocol() uint32 {
	if m != nil {
		return m.Protocol
	}
	return 0
}

func (m *PacketModel) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *PacketModel) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type AddPacketsRequest struct {
	Packets              []*PacketModel `protobuf:"bytes,1,rep,name=packets,proto3" json:"packets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AddPacketsRequest) Reset()         { *m = AddPacketsRequest{} }
func (m *AddPacketsRequest) String() string { return proto.CompactTextString(m) }
func (*AddPacketsRequest) ProtoMessage()    {}
func (*AddPacketsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e370a687125f60cd, []int{1}
}

func (m *AddPacketsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPacketsRequest.Unmarshal(m, b)
}
func (m *AddPacketsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPacketsRequest.Marshal(b, m, deterministic)
}
func (m *AddPacketsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPacketsRequest.Merge(m, src)
}
func (m *AddPacketsRequest) XXX_Size() int {
	return xxx_messageInfo_AddPacketsRequest.Size(m)
}
func (m *AddPacketsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPacketsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddPacketsRequest proto.InternalMessageInfo

func (m *AddPacketsRequest) GetPackets() []*PacketModel {
	if m != nil {
		return m.Packets
	}
	return nil
}

func init() {
	proto.RegisterType((*PacketModel)(nil), "packets.PacketModel")
	proto.RegisterType((*AddPacketsRequest)(nil), "packets.AddPacketsRequest")
}

func init() {
	proto.RegisterFile("packets.proto", fileDescriptor_e370a687125f60cd)
}

var fileDescriptor_e370a687125f60cd = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x49, 0x5a, 0xdb, 0x3a, 0xa5, 0x8a, 0x8b, 0x94, 0x65, 0x15, 0x0c, 0x3d, 0xe5, 0xb4,
	0x81, 0x78, 0xf2, 0x66, 0x15, 0xf1, 0x20, 0x4a, 0x09, 0x9e, 0xbc, 0x48, 0x9a, 0x8c, 0x21, 0x34,
	0x61, 0xd7, 0xec, 0xe4, 0xa0, 0xbf, 0xc6, 0xb3, 0xbf, 0x52, 0xba, 0xc9, 0x56, 0xb1, 0xb7, 0xcc,
	0x9b, 0x6f, 0x5e, 0xde, 0x3e, 0x98, 0xe9, 0x34, 0xdb, 0x20, 0x19, 0xa9, 0x1b, 0x45, 0x8a, 0x8d,
	0xfb, 0x51, 0x9c, 0x15, 0x4a, 0x15, 0x15, 0x46, 0x56, 0x5e, 0xb7, 0x6f, 0x11, 0xd6, 0x9a, 0x3e,
	0x3a, 0x4a, 0x5c, 0xfc, 0x5f, 0x52, 0x59, 0xa3, 0xa1, 0xb4, 0xd6, 0x1d, 0xb0, 0xf8, 0xf2, 0x60,
	0xba, 0xb2, 0x4e, 0x8f, 0x2a, 0xc7, 0x8a, 0x1d, 0x81, 0x5f, 0x6a, 0xee, 0x05, 0x5e, 0x38, 0x4b,
	0xfc, 0x52, 0x33, 0x06, 0x43, 0x53, 0x7e, 0x22, 0xf7, 0xad, 0x62, 0xbf, 0x99, 0x80, 0x89, 0x3d,
	0xce, 0x54, 0xc5, 0x07, 0x56, 0xdf, 0xcd, 0x6c, 0x0e, 0x23, 0x43, 0x29, 0xb5, 0x86, 0x0f, 0xed,
	0xa6, 0x9f, 0xd8, 0x15, 0x40, 0xd6, 0x60, 0x4a, 0x98, 0xbf, 0xa6, 0xc4, 0x0f, 0x02, 0x2f, 0x9c,
	0xc6, 0x42, 0x76, 0xe9, 0xa4, 0x4b, 0x27, 0x9f, 0x5d, 0xba, 0xe4, 0xb0, 0xa7, 0x97, 0xb4, 0xb8,
	0x85, 0x93, 0x65, 0x9e, 0x77, 0x21, 0x4d, 0x82, 0xef, 0x2d, 0x1a, 0x62, 0x12, 0x5c, 0x01, 0xdc,
	0x0b, 0x06, 0xe1, 0x34, 0x3e, 0x95, 0xae, 0x9f, 0x3f, 0xcf, 0x49, 0x1c, 0x14, 0x3f, 0xc0, 0xb8,
	0x77, 0x60, 0xd7, 0x00, 0xbf, 0x7e, 0x4c, 0xec, 0xee, 0xf6, 0x7e, 0x22, 0xe6, 0x7b, 0x01, 0xef,
	0xb6, 0xdd, 0xde, 0x9c, 0xbf, 0x4c, 0xf4, 0xa6, 0x88, 0x8a, 0x46, 0x67, 0xdf, 0xfe, 0xf1, 0x53,
	0x4d, 0xf2, 0xbe, 0xd1, 0x99, 0x5c, 0x6d, 0x29, 0xb3, 0x1e, 0x59, 0xfa, 0xf2, 0x27, 0x00, 0x00,
	0xff, 0xff, 0xca, 0x69, 0xf7, 0x1e, 0xb1, 0x01, 0x00, 0x00,
}
